import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Header/Navbar";
import Footer from "./components/Footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Providers } from "./components/providers";  // Make sure this is a wrapper for Redux or other global state providers

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  hero,
}: Readonly<{
  children: React.ReactNode;
  hero?: React.ReactNode; // Optional Hero Section
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <UserProvider>
            {/* Navbar */}
            <Navbar />

            {/* Hero Section (conditionally rendered) */}
            {hero && <div>{hero}</div>}

            {/* Main Content */}
            <main className="pt-16">{children}</main>

            {/* Footer */}
            <Footer />
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
